web:
  image: dnunez24/magento-nginx
  links:
    - app
  ports:
    - "80:80"
app:
  image: dnunez24/magento-php
  volumes_from:
    - appdata
  links:
    - db
    - search
  environment:
    MAGENTO_HOST: magento.local
    MAGENTO_ADMIN_FIRSTNAME: Admin
    MAGENTO_ADMIN_LASTNAME: User
    MAGENTO_ADMIN_USERNAME: admin
    MAGENTO_ADMIN_PASSWORD: p@ssw0rD
    MAGENTO_ADMIN_EMAIL: admin@example.com
    MAGENTO_LOCALE: en_US
    MAGENTO_DEFAULT_CURRENCY: USD
    MAGENTO_TIMEZONE: America/Los_Angeles
db:
  image: dnunez24/magento-percona
  ports:
    - "3306:3306"
  volumes_from:
    - dbdata
  environment:
    MYSQL_ROOT_PASSWORD: mage
    MYSQL_USER: mage
    MYSQL_PASSWORD: mage
    MYSQL_DATABASE: magento
search:
  image: dnunez24/magento-solr
  volumes_from:
    - searchdata
appdata:
  image: dnunez24/magento-php
  volumes:
    - .:/srv/magento
  command: /bin/echo "Magento app data"
dbdata:
  image: dnunez24/magento-percona
  volumes:
    - /var/lib/mysql
  command: /bin/echo "Magento MySQL data"
searchdata:
  image: dnunez24/magento-solr
  volumes:
    - /srv/solr/solr/data
  command: /bin/echo "Magento Solr data"
setup:
  image: dnunez24/magento-tools
  volumes_from:
    - appdata
  links:
    - app
    - db
    - search
  command: /usr/local/bin/install-magento
magerun:
  image: dnunez24/magento-tools
  volumes_from:
    - appdata
  links:
    - app
    - db
    - search
  entrypoint: ["n98-magerun", "--skip-root-check"]
  command: list
